FROM openjdk:11 as BUILD_IMAGE
RUN apt update && apt install maven -y
RUN git clone https://github.com/networknuts/devops-project-java-app.git
RUN cd vprofile-project && git chockout docker && mvn install

FROM tomcat:9-jre11
RUM rm -rvf /usr/local/tomcat/webapps/*
COPY --from=BUILD_IMAGE vprofile-project/target/vprofile-v2.war /usr/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh","run"]
